// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Dt2G5L9Jtv2kcqpymwEP10E-17biXOA',
    appId: '1:21579583285:web:012d72c25372c7bfed467c',
    messagingSenderId: '21579583285',
    projectId: 'see-r-36eee',
    authDomain: 'see-r-36eee.firebaseapp.com',
    storageBucket: 'see-r-36eee.appspot.com',
    measurementId: 'G-YBJZRNDLXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaDwpG1ZztQreO1i1SCAvB9oi_W_GOhs',
    appId: '1:21579583285:android:96ef2ffa985d89ceed467c',
    messagingSenderId: '21579583285',
    projectId: 'see-r-36eee',
    storageBucket: 'see-r-36eee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgTjPFMwvViX7A1NC2hZItasV6Jfmg5og',
    appId: '1:21579583285:ios:7f4aaa4ca9a56830ed467c',
    messagingSenderId: '21579583285',
    projectId: 'see-r-36eee',
    storageBucket: 'see-r-36eee.appspot.com',
    iosClientId: '21579583285-9b5olnb4b95u60cs9dbhmtksfkcc69ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.seer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgTjPFMwvViX7A1NC2hZItasV6Jfmg5og',
    appId: '1:21579583285:ios:7f4aaa4ca9a56830ed467c',
    messagingSenderId: '21579583285',
    projectId: 'see-r-36eee',
    storageBucket: 'see-r-36eee.appspot.com',
    iosClientId: '21579583285-9b5olnb4b95u60cs9dbhmtksfkcc69ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.seer',
  );
}
